on:
  issues:
    types: [edited, closed]

jobs:
  manage-blockers:
    runs-on: self-hosted
    steps:
      - name: Get issue details
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              ...context.repo,
              issue_number: context.issue.number
            });
            const blockedField = getBlockedField(issue); // parse references

            const openBlockers = await checkOpenIssues(blockedField);
            if (openBlockers.length > 0) {
              await setStatus('Blocked');
              await storePreviousStatus(issue); // label or project field
            } else {
              const prevStatus = await getPreviousStatus(issue);
              await setStatus(prevStatus || 'To-Do');
              await clearBlockedField();
            }
